[project]
name = "remotePathSync"
dynamic = ["version"]
requires-python = ">=3.10"
authors = [{ name = "Ben Rich", email = "benjamin.rich@colorado.edu" }]

dependencies = [
    "paramiko", # I believe this installs scp with it
]